CREATE TABLE dbs_USER(
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    vorname VARCHAR(255) NOT NULL,
    nachname VARCHAR(255) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (email)
);

CREATE TABLE dbs_VERTRIEBLER(
    vertriebnummer SERIAL UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT PK_VERTRIBELER PRIMARY KEY (vertriebnummer),
    CONSTRAINT FK_USER FOREIGN KEY(email) REFERENCES dbs_USER(email)
);

CREATE TABLE dbs_KUNDE(
    kundennummer SERIAL UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT PK_KUNDE PRIMARY KEY (kundennummer),
    CONSTRAINT FK_USER FOREIGN KEY(email) REFERENCES dbs_USER(email)
);

CREATE TABLE dbs_FAHRZEUG(
    marke VARCHAR(255) NOT NULL,
    beschreibung VARCHAR(255) NOT NULL,
    kraftstoff VARCHAR(255) NOT NULL,
    baujahr NUMERIC(4) NOT NULL,
    modell VARCHAR(255) NOT NULL,
    fahrgestellnummer VARCHAR(255) NOT NULL,
    kennzeichen VARCHAR(255) NOT NULL UNIQUE,
    vertriebler VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT PK_FAHRZEUG PRIMARY KEY (kennzeichen),
    CONSTRAINT FK_VERTRIBELER FOREIGN KEY (vertriebler) REFERENCES dbs_VERTRIEBLER(vertriebnummer)
);

CREATE TABLE dbs_KUNDE_RESERVIERT_FAHRZEUG(
    kundennummer VARCHAR(255) UNIQUE NOT NULL,
    kennzeichen VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT PK_KUNDE_RESERVIERT_FAHRZEUG PRIMARY KEY (kundennummer,kennzeichen),
    CONSTRAINT FK_FAHRZEUG FOREIGN KEY (kennzeichen) REFERENCES dbs_FAHRZEUG(kennzeichen),
    CONSTRAINT FK_KUNDE FOREIGN KEY (kundennummer) REFERENCES dbs_KUNDE(kundennummer)
);