DROP TABLE carlook.dbs_USER CASCADE;
DROP TABLE carlook.dbs_VERTRIEBLER CASCADE;
DROP TABLE carlook.dbs_KUNDE CASCADE;
DROP TABLE carlook.dbs_FAHRZEUG CASCADE;
DROP TABLE carlook.dbs_KUNDE_RESERVIERT_FAHRZEUG CASCADE;